gui:
  spinner:
    frames: ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']
    rate: 100
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --config ~/.config/lazygit/delta-themes.gitconfig --features arctic-fox
  autoForwardBranches: none
os:
  editPreset: 'nvim'
